Update repo URL in places
florence-social/mastodon-fork pull request #103
Opened 2019-06-19 00:44 UTC by clarfon

Updates software name to "Florence Mastodon" where applicable, and updates repository URL from tootsuite/mastodon to florence-social/mastodon-fork.

2019-06-19 01:28 UTC, mal0ki approved these changes

2019-06-19 01:31 UTC, clarfon commented
Note: just realised I used the wrong docker org so I'll fix that in a bit ><

2019-06-19 01:40 UTC, mal0ki requested changes
Fix the thing then :P

2019-06-19 05:53 UTC, clarfon commented
Fixed!

2019-06-20 00:06 UTC, mal0ki approved these changes

2019-06-20 15:21 UTC, jhaye approved these changes

2019-06-20 15:37 UTC, merged