Add version suffix for Florence
florence-social/mastodon-fork pull request #131
Opened 2019-07-10 02:00 UTC by 1011X

This adds `+florence` to the version string, and fixes a minor issue where there was an extra dot after the version due to improper formatting.

This fixes #99.

2019-07-12 23:44 UTC, clarfonthey requested changes
I feel like we need to revert back this entire file, honestly. I will take a stab at implementing the thing I discussed in the other thread at some point.

2019-07-13 01:27 UTC, 1011X commented
I can checkout the original file and just include the suffix if you think that'll help. Then the other changes can be implemented in a separate PR.

2019-07-14 21:20 UTC, clarfon commented
I opened #136 for tracking how we want to do the other thing; IMHO this should just revert back to the Mastodon version and then add the +florence suffix.

2019-07-14 22:24 UTC, clarfonthey approved these changes

2019-07-23 15:25 UTC, jhaye approved these changes

2019-07-23 15:31 UTC, merged