Update changelog for pre-release 0.1.1
florence-social/mastodon-fork pull request #147
Opened 2019-07-16 17:20 UTC by clarfon

This should be merged after #131.

2019-07-16 19:57 UTC, 1011X approved these changes

2019-07-23 19:08 UTC, 1011X requested changes
Seems the only thing left is to decide if we should thank those who chose to test-run our software, and then fill in the date for the changelog. Once that's done, v0.0.1.1 should be ready!

2019-07-26 00:10 UTC, clarfon commented
I updated the changelog with a date for Sunday, and I also put out a post on fedi to collect a list of people who started their own instances. We should be able to push this on Saturday and send out an official post on Sunday after our weekly meeting.

2019-07-28 02:19 UTC, clarfon commented
I updated it with a generic thank-you message as almost no one replied to my poll. We can collect a list of instances by 0.2.0.

2019-07-28 02:35 UTC, 1011X approved these changes

2019-07-28 08:22 UTC, jhaye approved these changes

2019-07-28 13:03 UTC, merged