i18n: Spanish translations
florence-social/mastodon-fork pull request #86
Opened 2019-06-09 18:36 UTC by 1011X

Reopening of #81 because of branch renaming.

Also added some changes mentioned by @skrlet13.

2019-06-09 18:41 UTC, clarfonthey submitted a review, later dismissed

2019-06-09 19:46 UTC, clarfonthey submitted a review, later dismissed

2019-06-12 23:43 UTC, scarlet-tobar requested changes
Good, just a detail, it must say "Denuncias hechas", not "Denuncias hechos".

2019-06-12 23:43 UTC, skrlet13 commented on config/locales/es.yml
> +        created_reports: Denuncias hechos por esta cuenta
"Denuncias hechas"

2019-06-12 23:43 UTC, skrlet13 commented on config/locales/es.yml
> +        targeted_reports: Denuncias hechos sobre esta cuenta
"Denuncias hechas"

2019-06-13 19:27 UTC, 1011X commented on config/locales/es.yml
> +        created_reports: Denuncias hechos por esta cuenta
Fixed!

2019-06-13 19:27 UTC, 1011X commented on config/locales/es.yml
> +        targeted_reports: Denuncias hechos sobre esta cuenta
Fixed!

2019-06-13 19:36 UTC, 1011X commented on config/locales/es.yml
> +    mutual: Recíproco
¿Está bien usar "recíproco" en vez de "mutuo" aquí? Tiene un significado similar y parece ser mas común.

2019-06-14 19:51 UTC, skrlet13 commented
Yo diría que si.

El jue., 13 jun. 2019 a las 15:36, 1011X (<notifications@github.com>)
escribió:

> *@1011X* commented on this pull request.
> ------------------------------
>
> In config/locales/es.yml
> <https://github.com/florence-social/mastodon-fork/pull/86#discussion_r293544597>
> :
>
> >    preferences:
>
>      other: Otros
>
> +    posting_defaults: Condición base de publicación
>
> +    public_timelines: Cronologías públicas
>
> +  relationships:
>
> +    activity: Actividad de cuenta
>
> +    dormant: Latente
>
> +    last_active: Última vez activo
>
> +    most_recent: Más reciente
>
> +    moved: Movido
>
> +    mutual: Recíproco
>
>
> ¿Está bien usar "recíproco" en vez de "mutuo" aquí? Tiene un significado
> similar y parece ser mas común.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/florence-social/mastodon-fork/pull/86?email_source=notifications&email_token=AKSK4D3U4U4ZXZYXQ4JUW6TP2KOUBA5CNFSM4HWMNDN2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB3QAMYQ#pullrequestreview-249562722>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKSK4DYRUUXZFBQMKW7CM6LP2KOUBANCNFSM4HWMNDNQ>
> .
>

2019-06-15 03:24 UTC, clarfonthey submitted a review, later dismissed

2019-06-17 11:10 UTC, mal0ki commented
Is there anything here that still needs to be addressed, otherwise I'll happily approve and merge.

2019-06-17 17:03 UTC, clarfon commented
@skrlet13 Seems to have gone through everything, so I think everything is good!

2019-06-17 17:09 UTC, clarfon commented
…although there seem to be some merge conflicts, so, @1011X will have to resolve those first.

2019-06-17 21:21 UTC, mal0ki approved these changes
I trust your judgement, and issues have been squashed

2019-06-17 22:33 UTC, clarfonthey approved these changes

2019-06-17 22:57 UTC, merged